//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dekanat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Rating { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> DormitoryNumber { get; set; }
        public Nullable<int> Dormitory_Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
    
        public virtual Dormitories Dormitories { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
